// Riddle of the day — 50 kid-friendly riddles, rotated by date, offline.

export const RIDDLES = [
  { q: 'What has hands but cannot clap?', a: 'A clock!' },
  { q: 'What gets wetter the more it dries?', a: 'A towel!' },
  { q: 'What has a face and two hands but no arms or legs?', a: 'A clock!' },
  { q: 'What has to be broken before you can use it?', a: 'An egg!' },
  { q: 'What goes up but never comes down?', a: 'Your age!' },
  { q: 'What has a neck but no head?', a: 'A bottle!' },
  { q: 'What kind of band never plays music?', a: 'A rubber band!' },
  { q: 'What has many teeth but cannot bite?', a: 'A comb!' },
  { q: 'What building has the most stories?', a: 'The library!' },
  { q: 'What is full of holes but still holds water?', a: 'A sponge!' },
  { q: 'What question can you never answer "yes" to?', a: 'Are you asleep yet?' },
  { q: 'What is always in front of you but can\'t be seen?', a: 'The future!' },
  { q: 'What can you catch but not throw?', a: 'A cold!' },
  { q: 'What kind of room has no doors or windows?', a: 'A mushroom!' },
  { q: 'What invention lets you look right through a wall?', a: 'A window!' },
  { q: 'I\'m tall when I\'m young and short when I\'m old. What am I?', a: 'A candle!' },
  { q: 'What has one eye but can\'t see?', a: 'A needle!' },
  { q: 'What runs all around a backyard, yet never moves?', a: 'A fence!' },
  { q: 'What can travel around the world while staying in a corner?', a: 'A stamp!' },
  { q: 'What has legs but doesn\'t walk?', a: 'A table!' },
  { q: 'What has a thumb and four fingers but is not a hand?', a: 'A glove!' },
  { q: 'What has a head and a tail but no body?', a: 'A coin!' },
  { q: 'Where does today come before yesterday?', a: 'In the dictionary!' },
  { q: 'What gets bigger the more you take away from it?', a: 'A hole!' },
  { q: 'What kind of tree fits in your hand?', a: 'A palm tree!' },
  { q: 'What has ears but cannot hear?', a: 'A cornfield!' },
  { q: 'What do you call a bear with no teeth?', a: 'A gummy bear!' },
  { q: 'What kind of cup doesn\'t hold water?', a: 'A cupcake!' },
  { q: 'What goes through towns and hills but never moves?', a: 'A road!' },
  { q: 'What month of the year has 28 days?', a: 'All of them!' },
  { q: 'What is so fragile that saying its name breaks it?', a: 'Silence!' },
  { q: 'What can fill a room but takes up no space?', a: 'Light!' },
  { q: 'If you drop me I crack, but smile at me and I smile back. What am I?', a: 'A mirror!' },
  { q: 'What word is spelled wrong in every dictionary?', a: 'Wrong!' },
  { q: 'What belongs to you but is used by everyone else?', a: 'Your name!' },
  { q: 'What has words but never speaks?', a: 'A book!' },
  { q: 'What kind of coat is best put on wet?', a: 'A coat of paint!' },
  { q: 'The more you take, the more you leave behind. What are they?', a: 'Footsteps!' },
  { q: 'What can you keep after giving it to someone?', a: 'Your word!' },
  { q: 'What has 13 hearts but no other organs?', a: 'A deck of cards!' },
  { q: 'What starts with T, ends with T, and has T in it?', a: 'A teapot!' },
  { q: 'What kind of ship has two mates but no captain?', a: 'A friendship!' },
  { q: 'What has cities but no houses, rivers but no water, and forests but no trees?', a: 'A map!' },
  { q: 'Which is heavier: a kilo of feathers or a kilo of rocks?', a: 'Neither — they weigh the same!' },
  { q: 'What five-letter word becomes shorter when you add two letters to it?', a: 'Short (+er)!' },
  { q: 'What do you find at the end of a rainbow?', a: 'The letter W!' },
  { q: 'What breaks when you say it?', a: 'Silence… wait, that one again? A secret!' },
  { q: 'I have keys but no locks, space but no rooms. You can enter but can\'t go outside. What am I?', a: 'A keyboard!' },
  { q: 'What animal is always at a baseball game?', a: 'A bat!' },
  { q: 'What did zero say to eight?', a: 'Nice belt!' },
];
