// Starter data seeded into a fresh database (both builds).

export const SEED_TASKS = [
  { name: 'Reading', emoji: '📚', kind: 'count', unit: 'pages', note_label: 'book title', has_note: true },
  { name: 'Song practice', emoji: '🎤', kind: 'count', unit: 'minutes', note_label: 'song name', has_note: true },
  { name: 'Piano practice', emoji: '🎹', kind: 'count', unit: 'minutes', note_label: 'piece name', has_note: true },
  { name: 'Craft work', emoji: '🎨', kind: 'check', note_label: 'what did you make?', has_note: true },
  { name: 'Arrange wardrobe', emoji: '👗', kind: 'check', has_note: false },
  { name: 'Yoga', emoji: '🧘', kind: 'check', has_note: false },
  { name: 'Miobrace', emoji: '😴', kind: 'check', has_note: false },
  { name: 'Sleep', emoji: '🛌', kind: 'count', unit: 'hours', has_note: false },
  { name: 'Water', emoji: '💧', kind: 'count', unit: 'glasses', has_note: false },
  { name: 'Fruits & veggies', emoji: '🍎', kind: 'count', unit: 'servings', has_note: false },
  { name: 'Screen time', emoji: '📺', kind: 'count', unit: 'hours', has_note: false },
  { name: 'Treats', emoji: '🍪', kind: 'count', unit: 'treats', has_note: false },
  { name: 'Toilet', emoji: '🚽', kind: 'check', has_note: false },
];

// 36 gentle, age-appropriate writing prompts. Rotation: one per day by date,
// no repeat for over a month; shuffle button picks a random different one.
export const SEED_PROMPTS = [
  'What made you smile today?',
  "Describe your day like you're telling a story to a friend.",
  "What's something new you learned or noticed today?",
  'If today was a color, what color would it be and why?',
  'What was the best thing you ate today?',
  'If you could relive one moment from today, which would it be?',
  'What song matches how you feel right now?',
  'Write about something small you saw today that most people would miss.',
  'What are you looking forward to tomorrow?',
  'If your pet (or a bird outside) could talk, what would it say about today?',
  'What made you laugh today — even a little?',
  "Describe today's weather like it's a character in a story.",
  'What was the trickiest part of your day, and how did it go?',
  'If today had a title like a book chapter, what would it be?',
  'Who did you talk to today? What do you remember from it?',
  "What's one thing you did today that you're quietly proud of?",
  'If you could send a message to yourself this morning, what would you say?',
  'What sounds did you hear today that you liked?',
  'Draw your day with words: what were the shapes and colors of it?',
  "What's a question you wondered about today?",
  'If today was a flavor of ice cream, what would it be?',
  'What did you daydream about today?',
  'Write about a place you were in today as if you were seeing it for the first time.',
  "What's something kind you did or saw someone do today?",
  'If you had one extra hour today, what would you have done with it?',
  'What was the coziest moment of your day?',
  'Describe something you touched today — how did it feel?',
  'If today was a scene in a movie, what music would be playing?',
  "What's one tiny goal for tomorrow? (Really tiny counts!)",
  'What surprised you today?',
  'Write a haiku about your day (5-7-5 syllables — or close enough!).',
  'What would your future self want to remember about today?',
  "What's something you're curious to try someday?",
  'If your day was an animal, which animal was it and why?',
  'What made today different from yesterday?',
  'Invent a new word that describes how today felt. What does it mean?',
];
