// Word of the day / fun fact bank — 100 entries, rotated by date, fully
// offline. type: 'word' has {word, def}; type: 'fact' has {fact}.

export const WORDS_AND_FACTS = [
  { type: 'word', word: 'Petrichor', def: 'The lovely smell of earth after it rains.' },
  { type: 'fact', fact: 'Octopuses have three hearts — and blue blood!' },
  { type: 'word', word: 'Serendipity', def: 'Finding something wonderful by happy accident.' },
  { type: 'fact', fact: 'Honey never spoils. Archaeologists found 3,000-year-old honey that was still good.' },
  { type: 'word', word: 'Luminous', def: 'Glowing, full of light.' },
  { type: 'fact', fact: 'A group of flamingos is called a "flamboyance".' },
  { type: 'word', word: 'Wanderlust', def: 'A strong wish to travel and explore the world.' },
  { type: 'fact', fact: 'Bananas are berries, but strawberries are not.' },
  { type: 'word', word: 'Effervescent', def: 'Bubbly and full of lively energy.' },
  { type: 'fact', fact: 'Sea otters hold hands while sleeping so they do not drift apart.' },
  { type: 'word', word: 'Quixotic', def: 'Dreamy and idealistic, chasing big impossible dreams.' },
  { type: 'fact', fact: 'The Eiffel Tower grows about 15 cm taller in summer because metal expands in heat.' },
  { type: 'word', word: 'Mellifluous', def: 'A sound that is sweet and smooth, like honey for your ears.' },
  { type: 'fact', fact: 'Cows have best friends and get stressed when separated.' },
  { type: 'word', word: 'Halcyon', def: 'Calm, peaceful, golden — like a perfect summer afternoon.' },
  { type: 'fact', fact: 'There are more stars in the universe than grains of sand on all Earth\'s beaches.' },
  { type: 'word', word: 'Ephemeral', def: 'Lasting only a short, precious moment.' },
  { type: 'fact', fact: 'Butterflies taste with their feet.' },
  { type: 'word', word: 'Sonder', def: 'Realizing every stranger has a life as full and complex as yours.' },
  { type: 'fact', fact: 'A day on Venus is longer than a year on Venus.' },
  { type: 'word', word: 'Resplendent', def: 'Dazzlingly shiny and impressive.' },
  { type: 'fact', fact: 'Wombat poop is cube-shaped. Really.' },
  { type: 'word', word: 'Ebullient', def: 'Overflowing with excitement and cheerfulness.' },
  { type: 'fact', fact: 'The heart of a blue whale is the size of a small car.' },
  { type: 'word', word: 'Labyrinth', def: 'A maze so twisty you could get wonderfully lost.' },
  { type: 'fact', fact: 'Sloths can hold their breath longer than dolphins — up to 40 minutes.' },
  { type: 'word', word: 'Zephyr', def: 'A soft, gentle breeze.' },
  { type: 'fact', fact: 'Some cats are allergic to humans.' },
  { type: 'word', word: 'Kaleidoscope', def: 'A tube of mirrors and colors that makes endless changing patterns.' },
  { type: 'fact', fact: 'Rainbows are actually full circles — we just see half from the ground.' },
  { type: 'word', word: 'Susurrus', def: 'A soft whispering or rustling sound, like leaves in the wind.' },
  { type: 'fact', fact: 'Hot water can freeze faster than cold water. Scientists still argue about why!' },
  { type: 'word', word: 'Incandescent', def: 'Glowing brightly, like a filament — or a brilliant idea.' },
  { type: 'fact', fact: 'A snail can sleep for three years.' },
  { type: 'word', word: 'Meraki', def: 'Doing something with your whole heart and soul in it.' },
  { type: 'fact', fact: 'The dot over the letters i and j is called a "tittle".' },
  { type: 'word', word: 'Aurora', def: 'Curtains of colored light dancing in the polar night sky.' },
  { type: 'fact', fact: 'Penguins propose with pebbles — they gift a nice stone to their chosen mate.' },
  { type: 'word', word: 'Whimsical', def: 'Playfully odd and fanciful in a delightful way.' },
  { type: 'fact', fact: 'Your nose can remember about 50,000 different smells.' },
  { type: 'word', word: 'Solstice', def: 'The longest or shortest day of the year, when seasons turn.' },
  { type: 'fact', fact: 'A bolt of lightning is five times hotter than the surface of the sun.' },
  { type: 'word', word: 'Nefelibata', def: '"Cloud-walker" — someone who lives in their imagination.' },
  { type: 'fact', fact: 'Tigers have striped skin, not just striped fur.' },
  { type: 'word', word: 'Crepuscular', def: 'Active at twilight, like fireflies and rabbits.' },
  { type: 'fact', fact: 'The Moon has moonquakes.' },
  { type: 'word', word: 'Idyllic', def: 'So peaceful and perfect it feels like a storybook.' },
  { type: 'fact', fact: 'Goats have rectangular pupils, which give them almost 360° vision.' },
  { type: 'word', word: 'Bibliophile', def: 'Someone who loves and collects books.' },
  { type: 'fact', fact: 'The first oranges were green, and carrots used to be purple.' },
  { type: 'word', word: 'Gossamer', def: 'Delicate and light as spider silk floating in the air.' },
  { type: 'fact', fact: 'Sharks existed before trees did.' },
  { type: 'word', word: 'Euphoria', def: 'A rush of pure happiness.' },
  { type: 'fact', fact: 'A cloud can weigh more than a million pounds — it just floats because it is spread out.' },
  { type: 'word', word: 'Vellichor', def: 'The strange wistfulness of old bookshops.' },
  { type: 'fact', fact: 'Dolphins have names for each other — special signature whistles.' },
  { type: 'word', word: 'Panacea', def: 'An imaginary cure for absolutely everything.' },
  { type: 'fact', fact: 'The inventor of the Frisbee was turned into a Frisbee after he died. His wish!' },
  { type: 'word', word: 'Lambent', def: 'Softly glowing or flickering, like candlelight on a wall.' },
  { type: 'fact', fact: 'Bees can recognize human faces.' },
  { type: 'word', word: 'Scintillate', def: 'To sparkle with quick flashes of light.' },
  { type: 'fact', fact: 'It rains diamonds on Neptune and Uranus.' },
  { type: 'word', word: 'Peregrinate', def: 'To wander from place to place on a long journey.' },
  { type: 'fact', fact: 'A hummingbird weighs less than a coin but can fly backwards.' },
  { type: 'word', word: 'Nostalgia', def: 'The warm ache of remembering good times gone by.' },
  { type: 'fact', fact: 'Astronauts grow up to 5 cm taller in space.' },
  { type: 'word', word: 'Verdant', def: 'Lush and green, bursting with growing things.' },
  { type: 'fact', fact: 'Some turtles can breathe through their bottoms. Elegant? No. True? Yes.' },
  { type: 'word', word: 'Quintessence', def: 'The purest, most perfect example of something.' },
  { type: 'fact', fact: 'The world\'s oldest known joke is over 4,000 years old.' },
  { type: 'word', word: 'Ethereal', def: 'So light and delicate it seems from another world.' },
  { type: 'fact', fact: 'Crows hold grudges — and remember kind humans too.' },
  { type: 'word', word: 'Sillage', def: 'The trail of perfume someone leaves behind in the air.' },
  { type: 'fact', fact: 'A "jiffy" is a real unit of time: 1/100th of a second.' },
  { type: 'word', word: 'Apricity', def: 'The warmth of the sun on a cold winter day.' },
  { type: 'fact', fact: 'Squirrels plant thousands of trees by forgetting where they buried their nuts.' },
  { type: 'word', word: 'Cynosure', def: 'The center of attention that everyone\'s eyes turn to.' },
  { type: 'fact', fact: 'The letter Q is the only letter that doesn\'t appear in any US state name.' },
  { type: 'word', word: 'Eloquence', def: 'Speaking so beautifully that words seem to sing.' },
  { type: 'fact', fact: 'A group of pugs is called a "grumble".' },
  { type: 'word', word: 'Hiraeth', def: 'A deep longing for a home you can\'t return to — or that never was.' },
  { type: 'fact', fact: 'Water bears (tardigrades) can survive in outer space.' },
  { type: 'word', word: 'Limerence', def: 'The floaty feeling of having a big crush.' },
  { type: 'fact', fact: 'Your brain uses about 20% of all your body\'s energy — thinking is hard work!' },
  { type: 'word', word: 'Petrify', def: 'To turn to stone — from fear, or over millions of years.' },
  { type: 'fact', fact: 'The unicorn is the national animal of Scotland.' },
  { type: 'word', word: 'Susurration', def: 'A soft murmur, like a crowd whispering far away.' },
  { type: 'fact', fact: 'There\'s a planet made largely of diamond, called 55 Cancri e.' },
  { type: 'word', word: 'Felicity', def: 'Intense happiness; also, the perfect choice of words.' },
  { type: 'fact', fact: 'Cats can\'t taste sweetness.' },
  { type: 'word', word: 'Oscillate', def: 'To swing back and forth in a steady rhythm.' },
  { type: 'fact', fact: 'The total weight of all ants on Earth is close to the weight of all humans.' },
  { type: 'word', word: 'Pulchritude', def: 'A fancy, funny-sounding word that simply means beauty.' },
  { type: 'fact', fact: 'Some frogs freeze solid in winter and thaw back to life in spring.' },
  { type: 'word', word: 'Sempiternal', def: 'Lasting forever and ever and ever.' },
  { type: 'fact', fact: 'You can\'t hum while holding your nose. (You just tried it, didn\'t you?)' },
  { type: 'word', word: 'Brontide', def: 'The low rumble of distant thunder.' },
  { type: 'fact', fact: 'Giraffes have the same number of neck bones as you: seven.' },
];
